---

- hosts: 'prod:&web'
  name: "WebServer Deployment Play"
  become: yes 
  become_method: sudo 
  tasks: 
    - name: Install Required Web Packages 
      apt: name=apache2 state=present

    - name: Start apache Service
      service: name=apache2 state=started

- hosts: 'prod:&db'
  name: "WebServer Deployment on DB Group Play"
  become: yes 
  become_method: sudo 
  tasks: 
    - name: Install Required Web Packages 
      apt: name=apache2 state=present

    - name: Start apache Service
      service: name=apache2 state=started

    - name: Install Git Packages
      apt: name=git state=present 
